import CategoryPage from "@/components/CategoryPage";

const computers = [
  {
    id: 1,
    name: "Gaming Desktop",
    image: "/category/computers/Gaming Desktop.jpg",
    price: 60,
    description: "High-performance desktop computer for gaming enthusiasts.",
    securityDeposit: 120,
    category: "Computers",
    city: "Mumbai",
  },
  {
    id: 2,
    name: "Ultrabook Laptop",
    image: "/category/computers/Ultrabook Laptop.jpg",
    price: 45,
    description: "Thin and light laptop for productivity on-the-go.",
    securityDeposit: 90,
    category: "Computers",
    city: "Bangalore",
  },
  {
    id: 3,
    name: "All-in-One PC",
    image: "/category/computers/All-in-One PC.jpg",
    price: 50,
    description: "Space-saving all-in-one computer for home or office use.",
    securityDeposit: 100,
    category: "Computers",
    city: "Delhi",
  },
  {
    id: 4,
    name: "Chromebook",
    image: "/category/computers/Chromebook.jpg",
    price: 25,
    description: "Affordable laptop running Chrome OS for basic computing needs.",
    securityDeposit: 50,
    category: "Computers",
    city: "Pune",
  },
  {
    id: 5,
    name: "Workstation PC",
    image: "/category/computers/Workstation PC.jpg",
    price: 70,
    description: "Powerful workstation for professional-grade tasks and rendering.",
    securityDeposit: 140,
    category: "Computers",
    city: "Hyderabad",
  },
  {
    id: 6,
    name: "Mini PC",
    image: "/category/computers/Mini PC.jpg",
    price: 30,
    description: "Compact desktop computer for basic home computing.",
    securityDeposit: 60,
    category: "Computers",
    city: "Chennai",
  },
  {
    id: 7,
    name: "Gaming Laptop",
    image: "/category/computers/Gaming Laptop.jpg",
    price: 55,
    description: "Portable laptop designed for high-performance gaming.",
    securityDeposit: 110,
    category: "Computers",
    city: "Kolkata",
  },
  {
    id: 8,
    name: "Tablet PC",
    image: "/category/computers/Tablet PC.jpg",
    price: 35,
    description: "Versatile tablet with detachable keyboard for 2-in-1 functionality.",
    securityDeposit: 70,
    category: "Computers",
    city: "Ahmedabad",
  },
  {
    id: 9,
    name: "Server",
    image: "/category/computers/Server.jpg",
    price: 80,
    description: "High-capacity server for business or advanced home networking.",
    securityDeposit: 160,
    category: "Computers",
    city: "Jaipur",
  },
  {
    id: 10,
    name: "Custom-Built PC",
    image: "/category/computers/Custom-Built PC.jpg",
    price: 65,
    description: "Customizable PC built to your specifications.",
    securityDeposit: 130,
    category: "Computers",
    city: "Lucknow",
  },
];

export default function ComputersCategory() {
  return <CategoryPage categoryName="Computers" items={computers} />;
}
