import CategoryPage from "@/components/CategoryPage";

const clothing = [
  {
    id: 1,
    name: "Formal Suit",
    image: "/category/clothing/Formal Suit.jpg",
    price: 40,
    description: "Elegant suit for formal occasions and business meetings.",
    securityDeposit: 80,
    category: "Clothing",
    city: "Delhi",
  },
  {
    id: 2,
    name: "Cocktail Dress",
    image: "/category/clothing/Cocktail Dress.jpg",
    price: 35,
    description: "Stylish dress perfect for cocktail parties and events.",
    securityDeposit: 70,
    category: "Clothing",
    city: "Mumbai",
  },
  {
    id: 3,
    name: "Winter Coat",
    image: "/category/clothing/Winter Coat.jpg",
    price: 30,
    description: "Warm and fashionable coat for cold weather.",
    securityDeposit: 60,
    category: "Clothing",
    city: "Shimla",
  },
  {
    id: 4,
    name: "Designer Handbag",
    image: "/category/clothing/Designer Handbag.jpg",
    price: 25,
    description: "Luxury handbag to complement any outfit.",
    securityDeposit: 50,
    category: "Clothing",
    city: "Bangalore",
  },
  {
    id: 5,
    name: "Tuxedo",
    image: "/category/clothing/Tuxedo.jpg",
    price: 45,
    description: "Classic tuxedo for black-tie events and galas.",
    securityDeposit: 90,
    category: "Clothing",
    city: "Chennai",
  },
  {
    id: 6,
    name: "Wedding Dress",
    image: "/category/clothing/Wedding Dress.jpg",
    price: 100,
    description: "Beautiful wedding dress for your special day.",
    securityDeposit: 200,
    category: "Clothing",
    city: "Jaipur",
  },
  {
    id: 7,
    name: "Ski Outfit",
    image: "/category/clothing/Ski Outfit.jpg",
    price: 50,
    description: "Complete ski outfit including jacket and pants for winter sports.",
    securityDeposit: 100,
    category: "Clothing",
    city: "Manali",
  },
  {
    id: 8,
    name: "Costume Set",
    image: "/category/clothing/Costume Set.jpg",
    price: 20,
    description: "Fun costume set for parties and events.",
    securityDeposit: 40,
    category: "Clothing",
    city: "Goa",
  },
  {
    id: 9,
    name: "Formal Shoes",
    image: "/category/clothing/Formal Shoes.jpg",
    price: 15,
    description: "Elegant shoes to match with formal attire.",
    securityDeposit: 30,
    category: "Clothing",
    city: "Hyderabad",
  },
  {
    id: 10,
    name: "Jewelry Set",
    image: "/category/clothing/Jewelry Set.jpg",
    price: 30,
    description: "Stunning jewelry set to accessorize your outfit.",
    securityDeposit: 60,
    category: "Clothing",
    city: "Kolkata",
  },
];

export default function ClothingCategory() {
  return <CategoryPage categoryName="Clothing" items={clothing} />;
}
