import CategoryPage from "@/components/CategoryPage";

const vehicles = [
  {
    id: 1,
    name: "Compact Car",
    image: "/category/vehicles/Compact Car.jpg",
    price: 50,
    description: "Fuel-efficient compact car for city driving.",
    securityDeposit: 100,
    category: "Vehicles",
    city: "Mumbai",
  },
  {
    id: 2,
    name: "SUV",
    image: "/category/vehicles/SUV.jpg",
    price: 80,
    description: "Spacious SUV perfect for family trips and outdoor adventures.",
    securityDeposit: 200,
    category: "Vehicles",
    city: "Delhi",
  },
  {
    id: 3,
    name: "Luxury Sedan",
    image: "/category/vehicles/Luxury Sedan.jpg",
    price: 100,
    description: "High-end sedan for a comfortable and stylish ride.",
    securityDeposit: 250,
    category: "Vehicles",
    city: "Bangalore",
  },
  {
    id: 4,
    name: "Electric Car",
    image: "/category/vehicles/Electric Car.jpg",
    price: 70,
    description: "Eco-friendly electric car with long range.",
    securityDeposit: 150,
    category: "Vehicles",
    city: "Hyderabad",
  },
  {
    id: 5,
    name: "Motorcycle",
    image: "/category/vehicles/Motorcycle.jpg",
    price: 40,
    description: "Powerful motorcycle for thrilling rides.",
    securityDeposit: 80,
    category: "Vehicles",
    city: "Chennai",
  },
  {
    id: 6,
    name: "Cargo Van",
    image: "/category/vehicles/Cargo Van.jpg",
    price: 65,
    description: "Spacious cargo van for moving or business use.",
    securityDeposit: 180,
    category: "Vehicles",
    city: "Kolkata",
  },
  {
    id: 7,
    name: "Convertible",
    image: "/category/vehicles/Convertible.jpg",
    price: 90,
    description: "Stylish convertible for enjoying open-air driving.",
    securityDeposit: 220,
    category: "Vehicles",
    city: "Ahmedabad",
  },
  {
    id: 8,
    name: "RV",
    image: "/category/vehicles/RV.jpg",
    price: 120,
    description: "Fully-equipped RV for comfortable road trips and camping.",
    securityDeposit: 300,
    category: "Vehicles",
    city: "Pune",
  },
  {
    id: 9,
    name: "Scooter",
    image: "/category/vehicles/Scooter.jpg",
    price: 25,
    description: "Convenient scooter for quick city commutes.",
    securityDeposit: 50,
    category: "Vehicles",
    city: "Jaipur",
  },
  {
    id: 10,
    name: "Bicycle",
    image: "/category/vehicles/Bicycle.jpg",
    price: 15,
    description: "Eco-friendly bicycle for exercise and short trips.",
    securityDeposit: 30,
    category: "Vehicles",
    city: "Lucknow",
  },
];

export default function VehiclesCategory() {
  return <CategoryPage categoryName="Vehicles" items={vehicles} />;
}
