import CategoryPage from "@/components/CategoryPage";

const electronics = [
  {
    id: 1,
    name: "4K Smart TV",
    image: "/category/electronics/tv.jpg",
    price: 50,
    description: "Ultra HD smart TV with streaming capabilities.",
    securityDeposit: 20,
    category: "Electronics",
    city: "Mumbai",
  },
  {
    id: 2,
    name: "Wireless Noise-Cancelling Headphones",
    image: "/category/electronics/Headphones.jpg",
    price: 15,
    description: "Premium wireless headphones with active noise cancellation.",
    securityDeposit: 5,
    category: "Electronics",
    city: "Bangalore",
  },
  {
    id: 3,
    name: "High-End Laptop",
    image: "/category/electronics/laptop.jpg",
    price: 40,
    description: "Powerful laptop suitable for work and gaming.",
    securityDeposit: 15,
    category: "Electronics",
    city: "Delhi",
  },
  {
    id: 4,
    name: "Smartphone",
    image: "/category/electronics/smartphone.jpg",
    price: 20,
    description: "Latest model smartphone with advanced features.",
    securityDeposit: 10,
    category: "Electronics",
    city: "Pune",
  },
  {
    id: 5,
    name: "Tablet",
    image: "/category/electronics/tablet.jpg",
    price: 25,
    description: "Versatile tablet for productivity and entertainment.",
    securityDeposit: 8,
    category: "Electronics",
    city: "Hyderabad",
  },
  {
    id: 6,
    name: "Gaming Console",
    image: "/category/electronics/Gaming Desktop.jpg",
    price: 30,
    description: "Popular gaming console with a selection of games.",
    securityDeposit: 12,
    category: "Electronics",
    city: "Chennai",
  },
  {
    id: 7,
    name: "Bluetooth Speaker",
    image: "/category/electronics/Bluetooth Speaker.jpg",
    price: 10,
    description: "Portable speaker with excellent sound quality.",
    securityDeposit: 3,
    category: "Electronics",
    city: "Kolkata",
  },
  {
    id: 8,
    name: "Smartwatch",
    image: "/category/electronics/Smartwatch.jpg",
    price: 15,
    description: "Feature-packed smartwatch for fitness and notifications.",
    securityDeposit: 5,
    category: "Electronics",
    city: "Ahmedabad",
  },
  {
    id: 9,
    name: "Drone",
    image: "/category/electronics/drone.jpg",
    price: 35,
    description: "High-quality drone with 4K camera for aerial photography.",
    securityDeposit: 15,
    category: "Electronics",
    city: "Jaipur",
  },
  {
    id: 10,
    name: "E-reader",
    image: "/category/electronics/E-reader.jpg",
    price: 12,
    description: "Digital e-reader with a large library of books.",
    securityDeposit: 4,
    category: "Electronics",
    city: "Lucknow",
  },
];

export default function ElectronicsCategory() {
  return <CategoryPage categoryName="Electronics" items={electronics} />;
}
