import CategoryPage from "@/components/CategoryPage";

const tools = [
  {
    id: 1,
    name: "Power Drill",
    image: "/category/tools/Power Drill.jpg",
    price: 15,
    description: "High-performance power drill for various projects.",
    securityDeposit: 5,
    category: "Tools",
    city: "Mumbai",
  },
  {
    id: 2,
    name: "Circular Saw",
    image: "/category/tools/Circular Saw.jpg",
    price: 20,
    description: "Precise circular saw for woodworking tasks.",
    securityDeposit: 7,
    category: "Tools",
    city: "Pune",
  },
  {
    id: 3,
    name: "Pressure Washer",
    image: "/category/tools/Pressure Washer.jpg",
    price: 25,
    description: "Powerful pressure washer for outdoor cleaning.",
    securityDeposit: 10,
    category: "Tools",
    city: "Bangalore",
  },
  {
    id: 4,
    name: "Lawn Mower",
    image: "/category/tools/Lawn Mower.jpg",
    price: 30,
    description: "Efficient lawn mower for garden maintenance.",
    securityDeposit: 12,
    category: "Tools",
    city: "Hyderabad",
  },
  {
    id: 5,
    name: "Welding Machine",
    image: "/category/tools/Welding Machine.jpg",
    price: 35,
    description: "Professional-grade welding machine for metal work.",
    securityDeposit: 15,
    category: "Tools",
    city: "Delhi",
  },
  {
    id: 6,
    name: "Air Compressor",
    image: "/category/tools/Air Compressor.jpg",
    price: 22,
    description: "Versatile air compressor for various applications.",
    securityDeposit: 8,
    category: "Tools",
    city: "Chennai",
  },
  {
    id: 7,
    name: "Generator",
    image: "/category/tools/Generator.jpg",
    price: 40,
    description: "Portable generator for outdoor events or emergencies.",
    securityDeposit: 18,
    category: "Tools",
    city: "Kolkata",
  },
  {
    id: 8,
    name: "Chainsaw",
    image: "/category/tools/Chainsaw.jpg",
    price: 28,
    description: "Powerful chainsaw for tree cutting and pruning.",
    securityDeposit: 10,
    category: "Tools",
    city: "Jaipur",
  },
  {
    id: 9,
    name: "Tile Cutter",
    image: "/category/tools/Tile Cutter.jpg",
    price: 18,
    description: "Precise tile cutter for home renovation projects.",
    securityDeposit: 6,
    category: "Tools",
    city: "Ahmedabad",
  },
  {
    id: 10,
    name: "Paint Sprayer",
    image: "/category/tools/Paint Sprayer.jpg",
    price: 24,
    description: "Efficient paint sprayer for large painting jobs.",
    securityDeposit: 9,
    category: "Tools",
    city: "Lucknow",
  },
];

export default function ToolsCategory() {
  return <CategoryPage categoryName="Tools" items={tools} />;
}
