import CategoryPage from "@/components/CategoryPage";

const cameras = [
  {
    id: 1,
    name: "DSLR Camera",
    image: "/category/cameras/dslrcamera.jpg",
    price: 40,
    description: "Professional-grade DSLR camera for high-quality photography.",
    securityDeposit: 80,
    category: "Cameras",
    city: "Delhi",
  },
  {
    id: 2,
    name: "Mirrorless Camera",
    image: "/category/cameras/Mirrorless Camera.jpg",
    price: 35,
    description: "Compact mirrorless camera with interchangeable lenses.",
    securityDeposit: 70,
    category: "Cameras",
    city: "Mumbai",
  },
  {
    id: 3,
    name: "Action Camera",
    image: "/category/cameras/camera.jpg",
    price: 20,
    description: "Rugged action camera for adventure sports and activities.",
    securityDeposit: 40,
    category: "Cameras",
    city: "Bangalore",
  },
  {
    id: 4,
    name: "360-Degree Camera",
    image: "/category/cameras/360-Degree Camera.jpg",
    price: 25,
    description: "Panoramic camera for immersive 360-degree photos and videos.",
    securityDeposit: 50,
    category: "Cameras",
    city: "Hyderabad",
  },
  {
    id: 5,
    name: "Instant Camera",
    image: "/category/cameras/Instant Camera.jpg",
    price: 15,
    description: "Fun instant camera for immediate photo prints.",
    securityDeposit: 30,
    category: "Cameras",
    city: "Chennai",
  },
  {
    id: 6,
    name: "Professional Video Camera",
    image: "/category/cameras/Professional Camera.jpg",
    price: 50,
    description: "High-end video camera for professional filmmaking.",
    securityDeposit: 100,
    category: "Cameras",
    city: "Kolkata",
  },
  {
    id: 7,
    name: "Drone with Camera",
    image: "/category/cameras/Drone with Camera.jpg",
    price: 45,
    description: "Aerial drone with high-resolution camera for unique perspectives.",
    securityDeposit: 90,
    category: "Cameras",
    city: "Pune",
  },
  {
    id: 8,
    name: "Underwater Camera",
    image: "/category/cameras/Underwater Camera.jpg",
    price: 30,
    description: "Waterproof camera for capturing underwater scenes.",
    securityDeposit: 60,
    category: "Cameras",
    city: "Ahmedabad",
  },
  {
    id: 9,
    name: "Medium Format Camera",
    image: "/category/cameras/Medium Format Camera.jpg",
    price: 60,
    description: "High-resolution medium format camera for studio photography.",
    securityDeposit: 120,
    category: "Cameras",
    city: "Jaipur",
  },
  {
    id: 10,
    name: "Vintage Film Camera",
    image: "/category/cameras/Vintage Film Camera.jpg",
    price: 22,
    description: "Classic film camera for enthusiasts and collectors.",
    securityDeposit: 44,
    category: "Cameras",
    city: "Lucknow",
  },
];

export default function CamerasCategory() {
  return <CategoryPage categoryName="Cameras" items={cameras} />;
}
