import CategoryPage from "@/components/CategoryPage";

const furniture = [
  {
    id: 1,
    name: "Comfortable Sofa",
    image: "/category/furniture/sofa.jpg",
    price: 30,
    description: "Plush three-seater sofa perfect for your living room.",
    securityDeposit: 10,
    category: "Furniture",
    city: "Mumbai",
  },
  {
    id: 2,
    name: "Dining Table Set",
    image: "/category/furniture/Dining Table Set.jpg",
    price: 40,
    description: "Elegant dining table with six chairs.",
    securityDeposit: 12,
    category: "Furniture",
    city: "Delhi",
  },
  {
    id: 3,
    name: "Queen Size Bed",
    image: "/category/furniture/Queen Size Bed.jpg",
    price: 35,
    description: "Comfortable queen size bed with headboard.",
    securityDeposit: 15,
    category: "Furniture",
    city: "Bangalore",
  },
  {
    id: 4,
    name: "Office Desk",
    image: "/category/furniture/officedesk.jpg",
    price: 25,
    description: "Spacious desk ideal for home office setup.",
    securityDeposit: 8,
    category: "Furniture",
    city: "Hyderabad",
  },
  {
    id: 5,
    name: "Bookshelf",
    image: "/category/furniture/self.jpg",
    price: 20,
    description: "Large bookshelf with adjustable shelves.",
    securityDeposit: 6,
    category: "Furniture",
    city: "Chennai",
  },
  {
    id: 6,
    name: "Armchair",
    image: "/category/furniture/Cozy Armchair.jpg",
    price: 15,
    description: "Cozy armchair perfect for reading or relaxing.",
    securityDeposit: 5,
    category: "Furniture",
    city: "Kolkata",
  },
  {
    id: 7,
    name: "Coffee Table",
    image: "/category/furniture/Coffee Table.jpg",
    price: 18,
    description: "Stylish coffee table for your living room.",
    securityDeposit: 6,
    category: "Furniture",
    city: "Pune",
  },
  {
    id: 8,
    name: "Wardrobe",
    image: "/category/furniture/Wardrobe.jpg",
    price: 28,
    description: "Spacious wardrobe with hanging space and drawers.",
    securityDeposit: 10,
    category: "Furniture",
    city: "Ahmedabad",
  },
  {
    id: 9,
    name: "TV Stand",
    image: "/category/furniture/TV Stand.jpg",
    price: 22,
    description: "Modern TV stand with storage compartments.",
    securityDeposit: 7,
    category: "Furniture",
    city: "Jaipur",
  },
  {
    id: 10,
    name: "Outdoor Patio Set",
    image: "/category/furniture/Outdoor Patio Set.jpg",
    price: 45,
    description: "Complete patio set for outdoor entertaining.",
    securityDeposit: 15,
    category: "Furniture",
    city: "Lucknow",
  },
];

export default function FurnitureCategory() {
  return <CategoryPage categoryName="Furniture" items={furniture} />;
}
